### ISSUE TITLE
Command roles' weights might be wrong

### ISSUE THREAD

**Issue by BozoDel** [Park-Station/Parkstation#104]
I'm not sure the way things are configured now is intentional or now, but I suspect it's not.

For one, the CSS has top weight, tied with HoP. I suspect it's just a leftover from the CSS/HoP split, and it's weird for CSS to be higher priority than, say, HoS.

Also a lot of people assume that the Station AI is high priority, but it's not a priority role at all.

**Comment by DEATHB4DEFEAT** [comment]
I believe all heads have the same higher priority over other roles, if the player sets multiple heads to the same priority it should either *pick the most recently set one* or *randomly pick one*

**Comment by BozoDel** [comment]
Hm, I might be way off base, cause I'm pretty illiterate in C#, and it was a while ago when I tried to figure this out (on WD code), and I didn't take any notes.

Some jobs have a weight specified in the files in Resources/Prototypes/Roles/Jobs. Only head roles have that, and on Wizard's Den, it's set to 20 for Captain and HoP, and 10 for the other heads. From what I understand, the game first tries to fill the roles with a higher weight. Please forgive me if I'm mistaken, or if Park does it differently.

**Comment by Pspritechologist** [comment]
You do seem to be correct! We'll get it patched.
HoP may still remain highest weighted, simply because the ability to manage IDs makes promoting _other_ Heads a lot easier, even if they don't rank above anyone. Station AI should have Captain level weight, that's huge. 
Thanks for bringing this up.
